#Motor GPIO Pins
StdByPin: 22  # this is the common pin
leftMotorPins: [12,23,24] # fill up with GPIO pins, PWMA, AIn1, AIn2
rightMotorPins: [13,25,5] # same as above
#Sensor GPIO Pins
trig: 19    # common trig pin
echo_left: 17 #left sensor echo pin
echo_fwd: 4 #forward sensor echo pin
echo_right: 16   #right sensor echo pin
#button pins
button_pin: 18

R: 0.032
L: 0.13
max_omega: 6.28
max_vel: 30.0
gain_ratio: 8.5 # pwm = u *gain_ratio
MAXGAIN: 75.0
FOREVER: 1000
PWM_FREQ: 50 # PWM Frequency in Hertz
Obstruction_Tolerance: 20.00 # in cm
Backup_Time: 0.5 # in seconds
Backup_Speed:  15
Obstruction_Type: ['LEFT', 'STRAIGHT', 'RIGHT']
roam_vel: 20 # roaming velocity in cm/s
roam_time: 1.5 # moving time per roaming cycle (seconds)
#linear_vel_controller_calib: .950
#angular_vel_controller_calib: -0.07
